### ISSUE TITLE
Unsubscribe without additional Parameters

### ISSUE THREAD

**Issue by TvP-Koch** [Gregor-Agnes/newsletter_subscribe#11]
If we include the Plugin "Unsubscribe from Adresslist" on a page with just the basic data (admin email address, Admin Name, Title of the Newsletter) provided in the Backend, the Frontend will render just an input-field for the mail address to be unsubscribed.  (as expected)

When this input is used to unsubscribe, the submission of the form ends up in an exception 

Argument 2 passed to Symfony\Component\Mime\Address::__construct() must be of the type string, null given, called in /var/www/vhosts/www.tredeundvonpein.de/htdocs/typo3conf/ext/newsletter_subscribe/Classes/Controller/SubscribeController.php on line 419

The library-function should be called with address and name of the recipient. 
As no name is provided the error is understandable. newsletter_subscribe should call the function either without a second argument (as then "emptystring" will be set by default) or with a valid string (e.g. "emptystring" or "mailaddress").

Thanks and keep up the good work.

**Comment by Gregor-Agnes** [comment]
Thx for reporting, fixed in 02024f05cc543fcb26ad9a3975f62f303211d83d
