### ISSUE TITLE
found some Viewhelper error when trying to configure the newsletter_subscribe extension in Typo3 10

### ISSUE THREAD

**Issue by use-r2122** [Gregor-Agnes/newsletter_subscribe#2]
![image](https://user-images.githubusercontent.com/72063058/94516655-e734e580-0243-11eb-879a-5616be491546.png)
![image](https://user-images.githubusercontent.com/72063058/94516696-ffa50000-0243-11eb-9aaa-a12a73d9bb0a.png)

**Comment by Gregor-Agnes** [comment]
#The standard templates use viewhelper from the extension vhs. I added vhs as a dependency.  83ac1fbb94c3de954a61091cbd6458b5de72f908
