### ISSUE TITLE
feature request: admin notification on unsubscribe

### ISSUE THREAD

**Issue by TvP-Koch** [Gregor-Agnes/newsletter_subscribe#27]
Currently it's possible to send an admin e-mail if someone confirms a subscribtion. 
Could this be extended so that an e-mail is sent also if someone confirms an unsubscription?

**Comment by Gregor-Agnes** [comment]
Thx for your proposal an yes, of course this can be extended.
Feel free to create a pull request. 

Nevertheless I will look into it the next time I find a bit of time to work on that extension :)

**Comment by Gregor-Agnes** [comment]
I think this is solved in c457f84b95ab12760a5b53cb7049da3e9b42c887
Thx!
