### ISSUE TITLE
Field "name" in tt_address not set

### ISSUE THREAD

**Issue by jacques2017** [Gregor-Agnes/newsletter_subscribe#3]
Hello,
how can the field "name" can be set? In personalized mails direct_mail is using this field.

**Comment by Gregor-Agnes** [comment]
Not possible at the moment. But you can add fields in your direct_mail templates according to [the documentation here](https://docs.typo3.org/typo3cms/extensions/direct_mail/stable/UsersManual/PersonalizingDirectMailContent/Index.html).

Last paragraph: "Additional fields from the recipient table (e.g. defined by an extension) can be configured in the Extension Manager. You have to switch to "Information" view of EXT:direct_mail and set a comma- separated list of DB fields in "Additional DB fields of the recipie..." (addRecipFields) to make more markers available. These can be used according to the pattern above like ###USER_<some field>###."

Thus you could use firstName and lastName.

**Comment by jacques2017** [comment]
Thanks,
can you please add this to the next version? In my installation I add in SubscribeController.php on line 253 and after line 323
this code:
$subscription->setName($subscription->getFirstName()." ".$subscription->getLastName());

**Comment by Gregor-Agnes** [comment]
Added it on line 253, that should be sufficient. 
Thx for the code 👍

**Comment by zabinetta** [comment]
Hi, 
could you add an if-clause? in my web-project, it's not mandatory to give your name for the newsletter. 
When we use the plugin now, the name-field is blank, but not NULL, and we don't see the email-address in TYPO3 list-view.
code in line 253:
`if($subscription->getFirstName() || $subscription->getLastName()){
            $subscription->setName($subscription->getFirstName()." ".$subscription->getLastName());
}`
with the best regards,
Sabine

**Comment by Gregor-Agnes** [comment]
Hi and thx for the hint. A pull request would be great. Nevertheless I will change the in an upcoming version.
