### ISSUE TITLE
Error "No E-Mail-Template found"

### ISSUE THREAD

**Issue by jacques2017** [Gregor-Agnes/newsletter_subscribe#4]
On a installation with only on language (german) I get this error. 
On a multilanguage-installation all is fine.
I can't find a solution.
I have copied the templates in different folder, but it doesn't help.

Can you help me?

**Comment by Gregor-Agnes** [comment]
Have you set 
```	
language = de
locale_all = de_DE.utf8
```
in your typoscript config section?

**Comment by jacques2017** [comment]
> Have you set
>
> language = de
> locale_all = de_DE.utf8
>
> in your typoscript config section?

Thanks, that was it. I use TYPO3 10 LTS and so I did only set the language on the site configuration.
