### ISSUE TITLE
Confirm actions not working in translation

### ISSUE THREAD

**Issue by TBschen** [Gregor-Agnes/newsletter_subscribe#44]
I tested this with TYPO3 10.4.21

I tried the subscription module in the normal language:
filled out the form (normal page), got a mail, clicked on the link to confirm: works!

Tried the same in a translation:
filled out the form (translated page), got a mail, clicked on the link to confirm: get an error page!

Not sure what the issue is. Could you do a quick check if you have the same behaviour?

**Comment by Gregor-Agnes** [comment]
Which translation did you use? Did you create a email-template for that language? https://github.com/Gregor-Agnes/newsletter_subscribe/tree/master/Resources/Private/Templates/Mail

What does the error say?

I could not confirm the error.

**Comment by TBschen** [comment]
I'll check tomorrow.

**Comment by Gregor-Agnes** [comment]
Closed due to inactivity. Feel free to reopen if problem persists.
