### ISSUE TITLE
Problem with Double Opt-In Link

### ISSUE THREAD

**Issue by SicorDev** [Gregor-Agnes/newsletter_subscribe#48]
Hello again,

Clicking the Double Opt-In Link twice will result in the error:

Page Not Found
The page did not exist or was inaccessible. Reason: Page not found

Would be cool if you could provide a fix, since this is rather confusing for the typical double click subscribers.

Greetings,
Manuel Rotschkar

**Comment by Gregor-Agnes** [comment]
Hm, what are the suggestions here? I thought, this is an non existing link which leads to an 404. What would you expect?

**Comment by Gregor-Agnes** [comment]
No further feedback, therefore closed. Feel free to reopen if desired.

**Comment by SicorDev** [comment]
Hello there, 

so it's been a while. The problem is still present and actually worse than I originally thought. 

It's actually not that subscribers deliberately doubleclick, but it's Outlook. When you click the confirm link there, it triggers the request once, I think for safety/security/virus checks and then it redirects to the page generating a second request, so the error appears, even though the user is properly subscribed.

Acceptable good solutions would be two:

1. If a confirm request comes for a user that is already confirmed, just render the "confirmed' answer once again without doing anything.

2. Instead of having a hot-fire confirm/cancel links directly in the mail, just redirect to a page containing those for the user to manually confirm. That's probably a little more work, but also a lot safer, since no virus scanner or similar can mistakenly send the confirm/cancel requests without user interaction.
