### ISSUE TITLE
Page error unsubscribed - maybe better solution with flash message

### ISSUE THREAD

**Issue by zabinetta** [Gregor-Agnes/newsletter_subscribe#63]
Dear Gregor,
when I double-unsubscribe, the subscribe-controller goes  'Page not found'.
would it maybe be better to deliver some 'sorry, this address has maybe been unsubscribed already'
with the best regards,
Sabine

**Comment by alexdpunkt** [comment]
I have the same problem, 404 on unsubscribe but the addresss gets deleted correctly.

**Comment by Gregor-Agnes** [comment]
fixed in be83196cc7fc9449c5e4f8909515fb27e18211c9
New option: set sendPageNotFoundOnInvalidConfirmation to 0 get a hint instead of 404
