### ISSUE TITLE
PHP v8.1 support

### ISSUE THREAD

**Issue by nollm** [Gregor-Agnes/newsletter_subscribe#70]
With Typo3 v11 and PHP v8.1 I get the following error.

`Oops, an error occurred! Code: 2022112810584043c7c180- Exception: PHP Warning: Undefined array key "news" in /var/www/typo3_www.xxx-xxxxxxxxx.de/typo3conf/ext/newsletter_subscribe/Classes/Traits/OverrideEmptyFlexformValuesTrait.php line 63`

Is it already compatible with PHP v8.1 or is it in the pipeline?

**Comment by Gregor-Agnes** [comment]
Not testet yet. Will look into it in the near future. Feel free to create a pull request in the meantime.

**Comment by Gregor-Agnes** [comment]
Fixed in b14cbde0f53ac578c90c421e67a4fe7f1d727b13
