### ISSUE TITLE
Design of unsubscribe

### ISSUE THREAD

**Issue by Kaliumiodid** [Gregor-Agnes/newsletter_subscribe#72]
Is it by purpose that the unsubscribe content element looks slightly different to the subscribe part? In my case, the text field for the email address is shorter, the button right next to it and the button has the default look.
Also, the unsubscribe mail is not using the template I placed in the templates directory; the subscribe mails use it.

**Comment by Gregor-Agnes** [comment]
Thx, will have look into it. Screenshots would be  nice :)

**Comment by Kaliumiodid** [comment]
For the email part:
I set the mailTemplateRootPath in the plugin's subscribe content element. So for the subscribe mails (Confirmation and AlreadySubscribed), my templates are used.

![image](https://user-images.githubusercontent.com/21020616/206656906-4b253a85-b2a0-476c-84a0-e8c40e57ca6f.png)

This field is missing in the unsubscribe part, but it seems to be required.
I am using the UI, because I could not manage to set up the templates path via typoscript.

**Comment by Gregor-Agnes** [comment]
Fixed in 50db127f979e3a0f55fa3e32d9f9e36c2fdf5396 and 822ca5963f3ebcb97641f483623cbe918367c4b8
