### ISSUE TITLE
Two colons

### ISSUE THREAD

**Issue by Kaliumiodid** [Gregor-Agnes/newsletter_subscribe#73]
I just found a small issue: Sometimes the texts have two colons. I saw it for example in the German translation youHaveUnsubscribed and subscribeAgain.
The root seems to be that there is a colon in the XLF file and also in the HTML file (in this case: Unsubscribe.html).

**Comment by Gregor-Agnes** [comment]
Fixed in 98d8f20c5308c663a7cae7e62a5f0df7083823da
