### ISSUE TITLE
firstName form-input

### ISSUE THREAD

**Issue by Hobokens** [Gregor-Agnes/newsletter_subscribe#77]
Hi @Gregor-Agnes ,

there is a small mistake in `ShowForm.html`:
`
<f:form.textfield property="firstName form-input" class="mt-1 block w-full" />`
It should be:
`<f:form.textfield property="firstName" class="form-input mt-1 block w-full" />`

**Comment by Gregor-Agnes** [comment]
fixed [a76d44b](https://github.com/Gregor-Agnes/newsletter_subscribe/commit/a76d44bb61f16323d53d159df7007df999e59930)
