### ISSUE TITLE
TypoScript setting name error `subscribePageUid` vs `subscribeFormPid`

### ISSUE THREAD

**Issue by cundd** [Gregor-Agnes/newsletter_subscribe#79]
Thank you for providing and maintaining this extension!

I noticed that there may be an error with the TypoScript setting. In [setup.typoscript](https://github.com/Gregor-Agnes/newsletter_subscribe/blob/822ca5963f3ebcb97641f483623cbe918367c4b8/Configuration/TypoScript/setup.typoscript#L81) `plugin.tx_newslettersubscribe.settings.subscribePageUid` is described as being used in the email templates, but the configuration appears to be only used in [Templates/Subscribe/Unsubscribe.html](https://github.com/Gregor-Agnes/newsletter_subscribe/blob/822ca5963f3ebcb97641f483623cbe918367c4b8/Resources/Private/Templates/Subscribe/Unsubscribe.html#L27).

The [confirmation email](https://github.com/Gregor-Agnes/newsletter_subscribe/blob/main/Resources/Private/Templates/Mail/de/Confirmation.html#L11) uses the configuration `settings.subscribeFormPid`.

I don't think that's a major problem, but it could lead to confusion.

**Comment by cundd** [comment]
Just recognized: Are the `settings` forwarded to the email templates at all?

**Comment by Gregor-Agnes** [comment]
fixed in b7cf70bdce1c29fca52eacac12cdcb5a19afa3d9
