### ISSUE TITLE
TYPO3 12

### ISSUE THREAD

**Issue by Hobokens** [Gregor-Agnes/newsletter_subscribe#81]
Thanks for the nice extension. Do you plan an upgrade to version 12?

**Comment by Gregor-Agnes** [comment]
Yes, I do. Can't tell yet, when I will. But it shouldn't be a very intense effort.

**Comment by SSFGizmo** [comment]
I have started in my fork
* https://github.com/SSFGizmo/newsletter_subscribe/tree/12.x

TODO
* replace f:link.action in AlreadySubscribed.html etc

**Comment by camCut** [comment]
> I have started in my fork

Hi, thanks for the extension.
Is there any update on this?

**Comment by Gregor-Agnes** [comment]
@camCut not from my site, sorry
