### ISSUE TITLE
Auto cancel/confirm through Outlook & Co.

### ISSUE THREAD

**Issue by SicorDev** [Gregor-Agnes/newsletter_subscribe#84]
Hello, 

this is a straight follow up to the closed issue #48 which I seemingly cannot reopen as suggested.

The problem is still present and actually worse than I originally thought.

It's actually not that subscribers deliberately doubleclick, but it's Outlook. When you click the confirm link there, it triggers the request once, I think for safety/security/virus checks and then it redirects to the page, thus generating a second request. So an error appears, even though the user actually got properly subscribed.

Acceptable good solutions would be two:

- If a confirm request comes for a user that is already confirmed, just render the "confirmed' answer once again without actually doing anything.
- Instead of having hot-fire confirm/cancel links directly in the mail, just redirect to a page containing those for the user to manually confirm. That's probably a little more work, but also a lot safer, since no virus scanner or similar can mistakenly send the confirm/cancel requests without user interaction.

Greetings,
Manuel

**Comment by Gregor-Agnes** [comment]
should be fixed in be83196cc7fc9449c5e4f8909515fb27e18211c9
The solution is to show a hint if already confirmed. Extra page does not prevent from double clicking the link on the page with same result.

**Comment by SicorDev** [comment]
I tested this with the most recent version, but didn't get a hint. Instead I got the error message just like before.
