### ISSUE TITLE
error on All Files	newsletter_subscribe\Classes\Domain\Repository\SubscriptionRepository.php

### ISSUE THREAD

**Issue by RZivaralam** [Gregor-Agnes/newsletter_subscribe#85]
hello, everyone,
I find a little error in SubscriptionRepository.php. $query->logicalAnd  must be  without [] 
thanks a lot 

    public function findOldUnvalidated(int $days, string $pids)
    {
        $query = $this->createQuery();
        $query->matching(
            $query->logicalAnd(
                    $query->lessThan('crdate', time() - 86400 * $days),
                    $query->equals('hidden', true),
                    $query->in('pid', explode(',', $pids)),
            )
        );
        $query->setLimit(10);
        
        return $query->execute();
    }

**Comment by Gregor-Agnes** [comment]
Fixed: ab7a841b0a5cb9efd68a7979e892d142fb9bad2f
