### ISSUE TITLE
[Feature Request] hCaptcha in Newsletter Unsubscribe

### ISSUE THREAD

**Issue by nollm** [Gregor-Agnes/newsletter_subscribe#86]
Is it possible to implement hCaptcha as option in the Newsletter Unsubscribe form too?
We had the situation that a bot created an unconfirmed tt_address entry and then send 300 times an unsubscribe mail.

**Comment by Gregor-Agnes** [comment]
First thought: maybe better to use the unsubsribe link in the newsletter only. And deactivate the unsubscribe link and form?

I am not sure if I got the problem right: Could you explain, what exactly happened?

**Comment by nollm** [comment]
Our customer has two pages.
One to subscribe and one to unsubscribe.
Probably someone has created a subscription but has not confirmed it.
Then a bot spamed the unsubscribe form with this unconfirmed email.
If the email exists you can unsubscribe as often as you like and an email will be sent each time.
For that problem I think hCaptcha should be used in ShowUnsubscribe.html in the same way as in ShowSubscribe.html.

**Comment by Gregor-Agnes** [comment]
Ok, I think I understand. I am quite busy and cannot implement that featur ATM. In the meantime, I appreciate, if you would create the enhancement and the according pull request.

Anyway: thx for reporting!

**Comment by nollm** [comment]
Since I am currently upgrading Typo3 for a customer, I found the time to implement the feature and created a pull request.

**Comment by Gregor-Agnes** [comment]
https://github.com/Gregor-Agnes/newsletter_subscribe/commit/621864a31c10f1c702769bafb20861d340b5685d
