### ISSUE TITLE
After confirm via email link: PHP Warning: compact(): Undefined variable $alreadySubscribed 

### ISSUE THREAD

**Issue by fischhase** [Gregor-Agnes/newsletter_subscribe#88]
Typo3 12.4.15
newsletter_subscribe  6.1.1

Hi Gregor,
after clicking the confirmation link in the subscription mail I got the error  PHP Warning: compact(): Undefined variable $alreadySubscribed in /usr/www/.../typo3conf/ext/newsletter_subscribe/Classes/Controller/SubscribeController.php line 507

I added in line 467:
$alreadySubscribed = false;

Now it works. 

Thanks
Martin

**Comment by fhamelin** [comment]
I have the same problem, everything works fine except the confirmation link.

@fischhase Maybe you could submit a pull request for the fix you proposed?  If you don't have time I could provide one myself to speed things up.

Thanks

**Comment by Gregor-Agnes** [comment]
Should be fixed with 481276b2c6234020066094ad969a28dfd333772e
