### ISSUE TITLE
useSimpleSpamPrevention crashes subscription

### ISSUE THREAD

**Issue by fischhase** [Gregor-Agnes/newsletter_subscribe#89]
Hi Gregor,

I had the problem, that by subscribing for a newsletter the form could not be send correctly. After sending, the URL changed to:
**/mypage?tx_newslettersubscribe_subscribe%5Baction%5D=createConfirmation&tx_newslettersubscribe_subscribe%5Bcontroller%5D=Subscribe&cHash=c9d0c5f3483c0a94c87cd2a46d5a1ecd** 
but the form loads again as it was. 

Then I deactivated _basic.useSimpleSpamPrevention_ in the Extension Configuration tool. After that, it worked. There seams to be a problem with the spam prevention. I checked for PHP errors but there weren't. 

Thanks 
Martin

**Comment by Gregor-Agnes** [comment]
Is fixed with: 0549b8172842719dc1fbfab2d7b213756b2aff51 0cddf31f9a2bd3fcc54c4bf65542d5676e6d3900 776859753862a2ba38827317aa975b0881029b1e 464c9b347e9221387e0eed075f7fc6e26dc818fd
